# Generated by Django 3.1.4 on 2021-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2_form', '0002_auto_20210528_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='tax_year',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=100),
        ),
    ]
