# Generated by Django 3.1.4 on 2021-06-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(max_length=100)),
                ('medicare', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.TextField(max_length=100)),
                ('tax', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.tax')),
            ],
        ),
    ]
