# Generated by Django 3.1.4 on 2021-06-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paystub_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annually',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='620', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='620', editable=False, max_length=100)),
                ('medicare', models.TextField(default='145', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bi_Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='23.85', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='23.85', editable=False, max_length=100)),
                ('medicare', models.TextField(default='5.58', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='1.72', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='1.72', editable=False, max_length=100)),
                ('medicare', models.TextField(default='0.40', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='51.67', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='51.67', editable=False, max_length=100)),
                ('medicare', models.TextField(default='12.08', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Once',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='620', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='620', editable=False, max_length=100)),
                ('medicare', models.TextField(default='145', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quartely',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='155', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='155', editable=False, max_length=100)),
                ('medicare', models.TextField(default='36.25', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semi_annually',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='310', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='310', editable=False, max_length=100)),
                ('medicare', models.TextField(default='72.50', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semi_monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='25.83', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='25.83', editable=False, max_length=100)),
                ('medicare', models.TextField(default='6.04', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal_tax', models.TextField(default='11.92', editable=False, max_length=100)),
                ('state_tax', models.TextField(max_length=100)),
                ('sdi', models.TextField(max_length=100)),
                ('work_comp', models.TextField(max_length=100)),
                ('tdi', models.TextField(max_length=100)),
                ('social_security', models.TextField(default='11.92', editable=False, max_length=100)),
                ('medicare', models.TextField(default='2.79', editable=False, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='tax',
        ),
        migrations.DeleteModel(
            name='TAX',
        ),
        migrations.AddField(
            model_name='state',
            name='Bi_Weekly_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.bi_weekly'),
        ),
        migrations.AddField(
            model_name='state',
            name='Semi_monthly_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.semi_monthly'),
        ),
        migrations.AddField(
            model_name='state',
            name='annually',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.annually'),
        ),
        migrations.AddField(
            model_name='state',
            name='daily_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.daily'),
        ),
        migrations.AddField(
            model_name='state',
            name='monthly_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.monthly'),
        ),
        migrations.AddField(
            model_name='state',
            name='once_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.once'),
        ),
        migrations.AddField(
            model_name='state',
            name='quartely_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.quartely'),
        ),
        migrations.AddField(
            model_name='state',
            name='semi_annually_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.semi_annually'),
        ),
        migrations.AddField(
            model_name='state',
            name='weekly_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paystub_generator.weekly'),
        ),
    ]
