# Generated by Django 3.1.4 on 2021-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystub_generator', '0002_auto_20210607_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annually',
            name='federal_tax',
            field=models.TextField(default='620', max_length=100),
        ),
        migrations.AlterField(
            model_name='annually',
            name='medicare',
            field=models.TextField(default='145', max_length=100),
        ),
        migrations.AlterField(
            model_name='annually',
            name='social_security',
            field=models.TextField(default='620', max_length=100),
        ),
        migrations.AlterField(
            model_name='bi_weekly',
            name='federal_tax',
            field=models.TextField(default='23.85', max_length=100),
        ),
        migrations.AlterField(
            model_name='bi_weekly',
            name='medicare',
            field=models.TextField(default='5.58', max_length=100),
        ),
        migrations.AlterField(
            model_name='bi_weekly',
            name='social_security',
            field=models.TextField(default='23.85', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily',
            name='federal_tax',
            field=models.TextField(default='1.72', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily',
            name='medicare',
            field=models.TextField(default='0.40', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily',
            name='social_security',
            field=models.TextField(default='1.72', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='federal_tax',
            field=models.TextField(default='51.67', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='medicare',
            field=models.TextField(default='12.08', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='social_security',
            field=models.TextField(default='51.67', max_length=100),
        ),
        migrations.AlterField(
            model_name='once',
            name='federal_tax',
            field=models.TextField(default='620', max_length=100),
        ),
        migrations.AlterField(
            model_name='once',
            name='medicare',
            field=models.TextField(default='145', max_length=100),
        ),
        migrations.AlterField(
            model_name='once',
            name='social_security',
            field=models.TextField(default='620', max_length=100),
        ),
        migrations.AlterField(
            model_name='quartely',
            name='federal_tax',
            field=models.TextField(default='155', max_length=100),
        ),
        migrations.AlterField(
            model_name='quartely',
            name='medicare',
            field=models.TextField(default='36.25', max_length=100),
        ),
        migrations.AlterField(
            model_name='quartely',
            name='social_security',
            field=models.TextField(default='155', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_annually',
            name='federal_tax',
            field=models.TextField(default='310', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_annually',
            name='medicare',
            field=models.TextField(default='72.50', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_annually',
            name='social_security',
            field=models.TextField(default='310', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_monthly',
            name='federal_tax',
            field=models.TextField(default='25.83', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_monthly',
            name='medicare',
            field=models.TextField(default='6.04', max_length=100),
        ),
        migrations.AlterField(
            model_name='semi_monthly',
            name='social_security',
            field=models.TextField(default='25.83', max_length=100),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='federal_tax',
            field=models.TextField(default='11.92', max_length=100),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='medicare',
            field=models.TextField(default='2.79', max_length=100),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='social_security',
            field=models.TextField(default='11.92', max_length=100),
        ),
    ]
