# Generated by Django 3.1.4 on 2021-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystub_generator', '0003_auto_20210607_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_upld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
